# Generated by Django 4.2 on 2023-05-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ENCRE', 'ENCRE'), ('KIT BIMS', 'KIT BIMS'), ('Imprimante', 'Imprimante'), ('SECURITE', 'SECURITE'), ('MAT BUREAU', 'MAT BUREAU'), ('ORDINATEUR', 'ORDINATEUR')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='hightech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(choices=[('TECHNO SPARK 8', 'TECHNO SPARK 8'), ('TECHNO CAMON 16', 'TECHNO CAMON 16'), ('CHARGEUR TECNO SPARK', 'CHARGEUR TECNO SPARK'), ('TABLETTE TECHNO P 701', 'TABLETTE TECHNO P 701'), ('TABLETTE TECHNO P 703', 'TABLETTE TECHNO P 703'), ('TABLETTE TECHNO PP7E', 'TABLETTE TECHNO PP7E')], max_length=100)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('num_serie', models.PositiveIntegerField(null=True)),
                ('imei', models.PositiveIntegerField(null=True)),
                ('emplacement', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('T14S GEN 1', 'T14S GEN 1'), ('T450S', 'T450S'), ('81HN', '81HN')], max_length=100)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('num_serie', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SortieMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('decharge', models.CharField(max_length=100)),
                ('utilisation', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('unite', models.CharField(max_length=10, null=True)),
                ('emplacement', models.CharField(choices=[('SALLE SPORT', 'SALLE SPORT'), ('SALLE SERVEUR', 'SALLE SERVEUR'), ('CENTRE TRANSIT', 'CENTRE TRANSIT'), ('MINAWAO', 'MINAWAO'), ('KOUSSERI', 'KOUSSERI'), ('KOUSSERI', 'KOUSSERI'), ('AIRD', 'AIRD')], max_length=25)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashb.category')),
            ],
        ),
    ]
