# Generated by Django 4.2 on 2023-05-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0003_laptop_emplacement_alter_hightech_emplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hightech',
            name='imei',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='hightech',
            name='num_serie',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='emplacement',
            field=models.CharField(choices=[('SALLE SPORT', 'SALLE SPORT'), ('SALLE SERVEUR', 'SALLE SERVEUR'), ('CENTRE TRANSIT', 'CENTRE TRANSIT'), ('MINAWAO', 'MINAWAO'), ('KOUSSERI', 'KOUSSERI'), ('KOUSSERI', 'KOUSSERI'), ('AIRD', 'AIRD')], max_length=25),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='num_serie',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
