# Generated by Django 4.2 on 2023-05-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0006_alter_hightech_emplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='imei',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
