# Generated by Django 4.2 on 2023-05-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0008_sortiemat1_delete_sortiemat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortiemat1',
            name='date_retour',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sortiemat1',
            name='date_sortie',
            field=models.DateField(null=True),
        ),
    ]
