# Generated by Django 4.2 on 2023-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0009_alter_sortiemat1_date_retour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortiemat1',
            name='info',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
