# Generated by Django 4.2 on 2023-05-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0010_alter_sortiemat1_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortiemat1',
            name='date_retour',
            field=models.DateField(blank=True, null=True),
        ),
    ]
