# Generated by Django 4.2 on 2023-06-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0014_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hightech',
            name='arrivage',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='hightech',
            name='date_entree',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='arrivage',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='date_entree',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='arrivage',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_entree',
            field=models.DateField(blank=True, null=True),
        ),
    ]
