# Generated by Django 4.2 on 2023-06-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0015_hightech_arrivage_hightech_date_entree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ENCRE', 'ENCRE'), ('TONER', 'TONER'), ('KIT BIMS', 'KIT BIMS'), ('IMPRIMANTE', 'IMPRIMANTE'), ('SECURITE', 'SECURITE'), ('MAT RESEAU', 'MAT RESEAU'), ('MAT BUREAU', 'MAT BUREAU'), ('ENREGISTREMENT', 'ENREGISTREMENT'), ('ORDINATEUR', 'ORDINATEUR'), ('YTELEPHONE', 'TELEPHONE')], max_length=25),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.CharField(choices=[('T14S GEN 1 (Lenovo)', 'T14S GEN 1 (Lenovo)'), ('T450S (Lenovo)', 'T450S (Lenovo)'), ('81HN (Lenovo)', '81HN (Lenovo)'), ('T14S GEN 3 (Lenovo)', 'T14S GEN 3 (Lenovo)'), ('P16 GEN 1 (Lenovo)', 'P16 GEN 1 (Lenovo)'), ('X1 EXTREME G 5 (Lenovo)', 'X1 EXTREME G 5 (Lenovo)')], max_length=100),
        ),
    ]
