# Generated by Django 4.2 on 2023-06-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0016_alter_category_name_alter_laptop_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hightech',
            name='emplacement',
            field=models.CharField(choices=[('SALLE SPORT', 'SALLE SPORT'), ('SALLE SERVEUR', 'SALLE SERVEUR'), ('CENTRE TRANSIT', 'CENTRE TRANSIT'), ('CARTON DIMA', 'CARTON DIMA'), ('MINAWAO', 'MINAWAO'), ('COFFRE BABA', 'COFFRE BABA'), ('KOUSSERI', 'KOUSSERI'), ('KOUSSERI', 'KOUSSERI'), ('AIRD', 'AIRD')], max_length=25),
        ),
    ]
