# Generated by Django 4.2 on 2023-06-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0018_alter_hightech_emplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='hightech',
            name='sortie',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=25, null=True),
        ),
    ]
