# Generated by Django 4.2 on 2023-06-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0022_laptop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hightech',
            name='user',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
