# Generated by Django 4.2 on 2023-06-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0023_hightech_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='emplacement',
            field=models.CharField(choices=[('SALLE SPORT', 'SALLE SPORT'), ('SALLE SERVEUR', 'SALLE SERVEUR'), ('CENTRE TRANSIT', 'CENTRE TRANSIT'), ('STAFF', 'STAFF'), ('AGENT ENREG', 'AGENT ENREG'), ('MINAWAO', 'MINAWAO'), ('KOUSSERI', 'KOUSSERI'), ('KOUSSERI', 'KOUSSERI'), ('AIRD', 'AIRD')], max_length=25),
        ),
    ]
