# Generated by Django 4.2 on 2023-06-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0024_alter_laptop_emplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qte_sortie',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
