# Generated by Django 4.2 on 2023-06-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0026_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='emplacement',
            field=models.CharField(choices=[('SALLE SPORT', 'SALLE SPORT'), ('SALLE SERVEUR', 'SALLE SERVEUR'), ('CENTRE TRANSIT', 'CENTRE TRANSIT'), ('STAFF', 'STAFF'), ('AGENT ENREG', 'AGENT ENREG'), ('BUREAU MINAWAO', 'BUREAU MINAWAO'), ('BUREAU KOUSSERI', 'BUREAU KOUSSERI'), ('BUREAU AIRD', 'BUREAU AIRD')], max_length=25),
        ),
    ]
