# Generated by Django 4.2 on 2023-06-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0027_alter_laptop_emplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hightech',
            name='emplacement',
            field=models.CharField(choices=[('SALLE SPORT', 'SALLE SPORT'), ('SALLE SERVEUR', 'SALLE SERVEUR'), ('CENTRE TRANSIT', 'CENTRE TRANSIT'), ('CARTON DIMA', 'CARTON DIMA'), ('SAC KAKI', 'SAC KAKI'), ('COFFRE BABA', 'COFFRE BABA'), ('BUREAU MINAWAO', 'BUREAU MINAWAO'), ('BUREAU KOUSSERI', 'BUREAU KOUSSERI'), ('BUREAU AIRD', 'BUREAU AIRD'), ('CARTON NEUF', 'CARTON NEUF')], max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='emplacement',
            field=models.CharField(choices=[('SALLE SPORT', 'SALLE SPORT'), ('SALLE SERVEUR', 'SALLE SERVEUR'), ('CENTRE TRANSIT', 'CENTRE TRANSIT'), ('BUREAU MINAWAO', 'BUREAU MINAWAO'), ('BUREAU KOUSSERI', 'BUREAU KOUSSERI'), ('BUREAU AIRD', 'BUREAU AIRD')], max_length=25),
        ),
    ]
