# Generated by Django 4.2 on 2023-06-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0030_alter_product_arrivage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arrivage',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON'), ('NEUF', 'NEUF')], max_length=25, null=True),
        ),
    ]
